CREATE DATABASE [AEXTestDB]
GO

USE [AEXTestDB]
GO

CREATE TABLE [dbo].[Movies] (
[Id] INT NOT NULL IDENTITY,
[Name] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
[RealeaseYear] DATE NOT NULL,
[Description] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE TABLE [dbo].[Actors] (
[Id] INT NOT NULL IDENTITY,
[FirstName] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
[MiddleName] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
[LastName] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
[Country] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE TABLE [dbo].[Genres] (
[Id] INT NOT NULL IDENTITY,
[Name] NVARCHAR(100) COLLATE Cyrillic_General_CI_AS_KS NOT NULL,
PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO

CREATE TABLE [dbo].[MoviesActors] (
[Id] INT NOT NULL IDENTITY PRIMARY KEY,
[ActorId] INT NOT NULL,
[MovieId] INT NOT NULL,
FOREIGN KEY ([ActorId]) REFERENCES [dbo].[Actors] ([Id]),
FOREIGN KEY ([MovieId]) REFERENCES [dbo].[Movies] ([Id])
);
GO

CREATE TABLE [dbo].[MoviesGenres] (
[Id] INT NOT NULL IDENTITY PRIMARY KEY,
[MovieId] INT NOT NULL,
[GenreId] INT NOT NULL,
FOREIGN KEY ([GenreId]) REFERENCES [dbo].[Genres] ([Id]),
FOREIGN KEY ([MovieId]) REFERENCES [dbo].[Movies] ([Id])
);
GO